// 샘플 데이터 - 고립·은둔 청년 상담/위로 커뮤니티용
export const myPosts = [
  {
    id: 1,
    title: '처음으로 산책 나갔어요',
    content: '오늘은 오랜만에 집 근처 공원을 다녀왔습니다. 혼자였지만 기분이 한결 나아졌어요.',
    date: '2024.03.16',
    likes: 42,
    comments: 12,
    views: 256,
    category: '경험담',
    status: 'published',
  },
  {
    id: 2,
    title: '혼자 밥 먹는 게 두려울 때',
    content: '밖에서 혼자 밥 먹는 게 아직 쉽지 않은데, 혹시 극복하신 분들 계신가요?',
    date: '2024.03.15',
    likes: 35,
    comments: 28,
    views: 189,
    category: '질문',
    status: 'published',
  },
  {
    id: 3,
    title: '작은 목표 세우기',
    content:
      '이번 주 목표는 아침에 일찍 일어나서 햇빛을 조금이라도 받는 거예요. 같이 해보실 분 있나요?',
    date: '2024.03.14',
    likes: 18,
    comments: 7,
    views: 132,
    category: '도전',
    status: 'published',
  },
  {
    id: 4,
    title: '우울할 때 도움이 된 음악',
    content: '제가 힘들 때 듣는 음악들을 정리해봤습니다. 혹시 추천곡 있으신가요?',
    date: '2024.03.13',
    likes: 53,
    comments: 21,
    views: 342,
    category: '정보공유',
    status: 'published',
  },
  {
    id: 5,
    title: '작은 성취도 괜찮습니다',
    content: '오늘 방 청소 조금 했습니다. 예전엔 시작조차 못했는데, 조금이라도 해낸 게 뿌듯해요.',
    date: '2024.03.12',
    likes: 61,
    comments: 33,
    views: 401,
    category: '격려',
    status: 'published',
  },
];

export const myComments = [
  {
    id: 1,
    postTitle: '처음으로 산책 나갔어요',
    comment: '정말 대단하세요! 저도 용기 내서 나가보고 싶네요.',
    date: '2024.03.16',
    likes: 14,
    author: '햇살찾는이',
    postCategory: '경험담',
  },
  {
    id: 2,
    postTitle: '혼자 밥 먹는 게 두려울 때',
    comment: '저도 그랬는데, 작은 카페에서 음료 하나부터 시작했어요. 조금씩 괜찮아지더라고요.',
    date: '2024.03.15',
    likes: 20,
    author: '조심스런도전',
    postCategory: '질문',
  },
  {
    id: 3,
    postTitle: '작은 목표 세우기',
    comment: '좋은 목표네요. 저도 내일부터 아침에 커튼 열기부터 해볼게요!',
    date: '2024.03.14',
    likes: 9,
    author: '같이걸어요',
    postCategory: '도전',
  },
  {
    id: 4,
    postTitle: '우울할 때 도움이 된 음악',
    comment: '저는 잔잔한 피아노 음악을 들어요. 마음이 조금 편해지더라고요.',
    date: '2024.03.13',
    likes: 11,
    author: '음악은힘',
    postCategory: '정보공유',
  },
  {
    id: 5,
    postTitle: '작은 성취도 괜찮습니다',
    comment: '정말 잘하셨어요! 작은 성취가 쌓이면 큰 변화를 만들 거예요.',
    date: '2024.03.12',
    likes: 22,
    author: '작은발걸음',
    postCategory: '격려',
  },
];

export const likedPosts = [
  {
    id: 1,
    title: '혼자가 아니에요',
    author: '마음나누기',
    date: '2024.03.16',
    likes: 78,
    comments: 45,
    category: '위로',
    excerpt: '지금 이 글을 읽는 당신도 혼자가 아닙니다. 우리 모두 같은 길을 걷고 있어요.',
  },
  {
    id: 2,
    title: '작은 루틴 만들기',
    author: '새벽햇살',
    date: '2024.03.15',
    likes: 63,
    comments: 30,
    category: '도움글',
    excerpt: '매일 같은 시간에 일어나거나 차를 끓이는 작은 루틴이 마음을 안정시켜줍니다.',
  },
  {
    id: 3,
    title: '불안할 때 호흡법',
    author: '숨고르기',
    date: '2024.03.14',
    likes: 85,
    comments: 39,
    category: '정보공유',
    excerpt:
      '코로 깊게 들이마시고, 입으로 천천히 내쉬는 호흡법이 불안을 완화하는 데 도움이 됩니다.',
  },
  {
    id: 4,
    title: '나를 위한 칭찬',
    author: '자존감회복',
    date: '2024.03.13',
    likes: 91,
    comments: 52,
    category: '격려',
    excerpt: '아무것도 안 한 것 같아도, 오늘 하루를 견딘 것만으로 충분히 잘한 거예요.',
  },
];
